### ISSUE TITLE
missing hook_config_info() prevents config sync

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/email_contactform#4]
Since this module uses a config file for it's settings, it should have an implementation of `hook_config_info()` so that the files can sync.

**Comment by stpaultim** [comment]
I am reopening this issue, because I am doing some experiments with config management and trying to deploy one of my production sites in a local environment using config import. 

I'm getting this error:

`The configuration "email_contactform.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.`

I found this core issue, which pointed at hook_config_info in a contrib module as a possible culprit. 
https://github.com/backdrop/backdrop-issues/issues/4160

I have checked and Email Contact Form is enabled on both the original site and the destination site, so I'm not sure why I'm getting this error. 

If I understand correctly, at @klonos says that his core PR might fix this problem.
https://github.com/backdrop/backdrop-issues/issues/5163

**Comment by klonos** [comment]
The change @jenlampton merged back in Nov. 2017 should fix this, but it is not included in the official release of the module. A fresh release should fix this 😉

**Comment by jenlampton** [comment]
yes, can do.

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop-contrib/email_contactform/releases/tag/1.x-1.3.0

**Comment by stpaultim** [comment]
Just confirming that I updated the module on my site and the problem was fixed! THANKS!
